[package]
name = "rustbu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# easycookie = "1.0.3"
rand = "0.8.5"
# reqwest = "0.11.23"
rocket = "0.5.0"
# serde = "1.0.195"
# serde_json = "1.0.111"
